### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by zzz6519003** [kengoldfarb/pin-it-node#14]
1) pin it should be able to pin with valid username, password, and boardId:
     Uncaught TypeError: Cannot read property 'statusCode' of undefined
      at Request._callback (node_modules/pin-it-node/index.js:83:72)

**Comment by kengoldfarb** [comment]
Thanks.  I'll take a look into this soon.

**Comment by kengoldfarb** [comment]
It looks like I'm missing some required packages in tests/package.json (like lodash), but I'm seeing the tests pass once that's fixed...

```
Success!  New pin has been added to the board.
    ✓ should be able to pin with valid username, password, and boardId (8041ms)
Success!  The board has been created.
    ✓ should be able to create a board (4884ms)
Success!  The board has been deleted.
    ✓ should be able to delete a board (4608ms)
Success!  Pin deleted
    ✓ should be able to delete a pin (8681ms)


  4 passing (26s)
```

The error you're getting indicates that there is no response coming back when it makes the initial request to pinterest which is very strange.  There should be some type of response unless it can't connect (i.e. not connected to the internet or maybe an SSL error).  Are you seeing this error only in the test?  Have you been able to pin just using the library in your own program?

Based on where the error is occurring it probably doesn't matter, but did you update the `username`, `password`, and `boardId` in the [test case](https://github.com/kengoldfarb/pin-it-node/blob/0.2.0/tests/pinItTests.js#L9) before running the test?

I'll keep this open because even if I can't recreate the issue, there should be a check that response is defined before using the status code.

**Comment by zzz6519003** [comment]
Hi! I ll do it when i have time  thx!
